### ISSUE TITLE
[Issue]: Can't rip subs for movie even though it has ~30

### ISSUE THREAD

**Issue by insurw** [MichaelYochpaz/iSubRip#33]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.10.7

### Package Version

2.3.2

### Description

I can't rip [Bullet Train](https://itunes.apple.com/us/movie/bullet-train/id1635627017) subs for some reason. I thought maybe it was because it's _buy only_, but Thor: Love and Thunder doesn't have the issue.

### Config

```TOML
[general]
check-for-updates = true

[downloads]
folder = "C:\\Users\\insurw-su\\Downloads"
format = "srt"
#languages = ["en", "en-US", "sv", "sv-SE", "da", "da-DK", "no", "no-NO", "fi", "fi-FI"]
languages = []
merge-playlists = false
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
zip = true

[scraping]
# User-Agent to use while scraping iTunes.
# Don't change this unless you know what you're doing.
itunes-user-agent = "iTunes-AppleTV/15.2"

# User-Agent to use while scraping AppleTV.
# Don't change this unless you know what you're doing.
appletv-user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"

[subtitles]
fix-rtl = false
rtl-languages = ["ar", "he"]
remove-duplicates = true
```

### Output Log

```Text
isubrip https://itunes.apple.com/se/movie/bullet-train/id1635627017?l=en
Scraping https://itunes.apple.com/se/movie/bullet-train/id1635627017?l=en...
Found movie: Bullet Train
Error: No valid playlist could be found.

isubrip https://itunes.apple.com/us/movie/bullet-train/id1635627017
Scraping https://itunes.apple.com/us/movie/bullet-train/id1635627017...
Found movie: Bullet Train
Error: No valid playlist could be found.
```
