### ISSUE TITLE
[Issue]: "An iTunes offer could not be found. Skipping..."

### ISSUE THREAD

**Issue by Ob1w4** [MichaelYochpaz/iSubRip#36]
### Confirmations

- [X] I confirm that I checked the issues tab and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.10.5

### Package Version

2.3.3

### Description

When I try to get the French subtitles for this link: https://tv.apple.com/fr/movie/the-score/umc.cmc.64dyhbdttzmnf1yghg8tbd9lh, isubrip says: "An iTunes offer could not be found. Skipping...".

But the Apple TV page lists French subtitles as available.

### Config

```TOML
[downloads]
folder = "C:\\Users\\Admin\\Desktop\\"
format = "vtt"
languages = ["en-US", "en-GB", "fr-FR","fr"]
zip = false

[subtitles]
fix-rtl = false

check-for-updates = true
```

### Output Log

```Text
C:\Users\Admin>isubrip https://tv.apple.com/fr/movie/the-score/umc.cmc.64dyhbdttzmnf1yghg8tbd9lh
Scraping https://tv.apple.com/fr/movie/the-score/umc.cmc.64dyhbdttzmnf1yghg8tbd9lh...
An iTunes offer could not be found. Skipping...
```
