### ISSUE TITLE
[Issue]: whenever isubrip finds a subtitles file, python crashes.

### ISSUE THREAD

**Issue by yoavoffek** [MichaelYochpaz/iSubRip#50]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.11.4

### Package Version

2.4.3

### Description

whenever I try to download any subtitle to any path that's not the isubrip folder, and isubrip does indeed find a subtitles file, as soon as it does, python crashes.
I've tried debugging this problem, steps included running isubrip on a different computer (on which it worked perfectly). completely uninstalling and purging all libraries and modules, then reinstalling everything (which did not work). downgrading to an older version of python.
nothing seems to work.

when debugging, I came across an error that seemed to indicate that this is a permissions error, and so I tried to run isubrip as admin, but still I keep on getting the same error.

the odd thing is that when I hit "close program" on the "python has crashed" window that gets prompted, isubrip does indeed download the desired subtitle to the folder specified in the config file.
I've been trying to debug this for the past two weeks to no avail, which is why I'm now submitting this report.

just to clarify, I'm using the administrator user of said computer (so there shouldn't be and read/write permission problems), and cmd is running on either admin or system permissions, yet still python crashes on both.

when debugging, this is the error I got:
Unhandled exception at 0x00007FF8EE9CBA44 (python311.dll) in python.exe: 0xC0000005: Access violation reading location 0x0000000000000008.

### Output Log

```Text
Scraping https://tv.apple.com/il/movie/the-little-mermaid/umc.cmc.gto5t9phvu7dpajarqglrfmh
Found movie: The Little Mermaid (2023)
עברית (he) subtitles were successfully downloaded.
עברית (forced) (he) subtitles were successfully downloaded.

2/2 matching subtitles have been successfully downloaded.

#then after that python crashes, and displays the subtitles in the folder, only after I press "close program", as stated in the description.
```

### Config

```TOML
[general]
check-for-updates = true

[downloads]
folder = "C:\\Users\\Administrator\\Documents\\ATV-Downloads"
format = "srt"
languages = [
    "he",
    "he-IL",
]
overwrite-existing = true
merge-playlists = false
zip = false

[subtitles]
remove-duplicates = true
convert-to-srt = true

[scrapers]
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
```
