### ISSUE TITLE
[Issue]: Some rips doesn't seem to use specified URL

### ISSUE THREAD

**Issue by insurw** [MichaelYochpaz/iSubRip#69]
### Confirmations

- [X] I have checked the issues tab, and couldn't find an existing open issue for the issue I want to report.

### OS Type

Windows

### Python Version

3.12.3

### Package Version

2.5.4

### Description

isubrip log seems to indicate it's using the URL specified but doesn't and rips languages that aren't listed. It doesn't matter if isubrup settings is set to rip all or specific languages. It uses wrong URL in both cases.

URL: https://tv.apple.com/se/movie/in-bruges/umc.cmc.3hfzzmfjj39s02vwynx3b91ih

I tested these movies with only Nordic subs and they rip correctly:
https://tv.apple.com/se/movie/kill-chain/umc.cmc.4d93g7p1rgs2jaqk2wyb878xb
https://tv.apple.com/se/movie/sameblod/umc.cmc.7574jgktfqv2sj5rimnwizy2f
https://tv.apple.com/se/movie/point-break/umc.cmc.xmw67i1eh8yv86pkhougfr33

### Output Log

```Text
Scraping 'https://tv.apple.com/se/movie/in-bruges/umc.cmc.3hfzzmfjj39s02vwynx3b91ih'...
Found movie: In Bruges [2008] (ID: 772060987)
'Espa単ol (Espa単a) (es-ES)' subtitles were successfully downloaded.
'Italiano (it)' subtitles were successfully downloaded.
'Nederlands (nl)' subtitles were successfully downloaded.
'English (US) (en-US) [CC]' subtitles were successfully downloaded.
4/4 matching subtitles were successfully downloaded.
```

### Config

```TOML
[general]
check-for-updates = true


[downloads]
# Folder to downloads files to.
# The default "." value means it will download to the same folder the script ran from.
# Use double backslashes in path to avoid escaping characters. Example: "C:\\Users\\<username>\\Downloads\\"
folder = "."

# A list of iTunes language codes to download.
# An empty array (like the one currently being used) will result in downloading all of the available subtitles.
# Example: ["en-US", "fr-FR", "he"]
#languages = ["en", "en-US", "en-UK", "sv", "sv-SE", "da", "da-DK", "no", "no-NO", "fi", "fi-FI"]
languages = []

# Whether to overwrite existing subtitles files.
# If set to false, names of existing subtitles will have a number appended to them to avoid overwriting.
# Value can be either "true" or "false".
overwrite-existing = false

# Save files into a zip archive if there is more than one matching subtitles.
# Value can be either "true" or "false".
zip = true


[subtitles]
# Fix RTL (Right To Left) for languages set on `fix-rtl-languages`.
# Value can be either "true" or "false".
#
# NOTE: This is off by default as some subtitles use other methods to fix RTL (like writing punctuations backwards).
#       Using this option on these type of subtitles can break the already-fixed RTL issues.
fix-rtl = false

# List of iTunes language codes to fix RTL on.
# This setting is optional, and is used for overriding the default list of languages to fix RTL on.
# This setting is not set by default.
rtl-languages = ["ar", "he"]

# Remove duplicate paragraphs (same text and timestamps).
remove-duplicates = true

# Whether to convert subtitles to SRT format.
# NOTE: This can cause loss of subtitles metadata that is not supported by SRT format.
convert-to-srt = false


[scrapers]
# User-Agent to use by default for all HTTP requests.
# Will be overridden by scraper-specific user-agent (if set).
default-user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"


[scrapers.itunes]
# User-Agent to use while scraping from iTunes.
# Changing this setting is not recommended.
# This setting is not set by default.
user-agent = "iTunes-AppleTV/15.2"


[scrapers.appletv]
# User-Agent to use while scraping from AppleTV.
# Changing this setting is not recommended.
# This setting is not set by default.
user-agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36"
```
